name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - master
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-24.04
    if: ${{ github.ref_name == github.event.repository.default_branch || (github.event_name == 'release' && github.event.action == 'published') }}
    permissions:
      contents: write
      id-token: write
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Cache
<<<<<<< before updating
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
=======
        uses: actions/cache@v4
>>>>>>> after updating
        with:
          path: |
            ~/vcpkg
            ~/.cache/pip
            ~/.cache/vcpkg
          key: x64-linux-gcc-14-${{ hashFiles('vcpkg.json') }}
          restore-keys: x64-linux-gcc-14-${{ hashFiles('vcpkg.json') }}

      - uses: aminya/setup-cpp@v1
        with:
          compiler: gcc-14
          cmake: true
          ninja: true
          ccache: true
          doxygen: true

<<<<<<< before updating
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
=======
      - uses: actions/setup-python@v5
>>>>>>> after updating
        with:
          python-version: 3.x

      - name: Configure
        run: >
          make cmake-configure CONFIGURE="
          -DCMAKE_BUILD_TYPE=RelWithDebInfo
          -DCMAKE_CXX_STANDARD=20
          -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
          -DVCPKG_TARGET_TRIPLET=x64-linux
          "

      - name: Build Docs
        run: make docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
